import type { Metadata } from 'next';
import { Play } from 'next/font/google';

import AuthProvider from '@/providers/Auth';

import './globals.css';

const play = Play({
  variable: '--font-play',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          antialiased
          ${play.variable}
          font-sans
        `}
      >
        <AuthProvider>
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
